[package]
name = "CHIP8-1"
version = "0.1.0"
authors = ["Jan Krüger <jan@krueger-jan.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
minifb = "0.17.0"
